name: Deploy

on:
  push:
    branches:
      - main

jobs:
      

  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Build Project
      run: npm build
      env:
        VITE_FIREBASE_APIKEY: ${{ secrets.VITE_FIREBASE_APIKEY }}
        VITE_FIREBASE_AUTHDOMAIN: ${{ secrets.VITE_FIREBASE_AUTHDOMAIN }}
        VITE_FIREBASE_PROJECTID: ${{ secrets.VITE_FIREBASE_PROJECTID }}
        VITE_FIREBASE_STORAGEBUCKET: ${{ secrets.VITE_FIREBASE_STORAGEBUCKET }}
        VITE_FIREBASE_MESSAGINGSENDERID: ${{ secrets.VITE_FIREBASE_MESSAGINGSENDERID }}
        VITE_FIREBASE_APPID: ${{ secrets.VITE_FIREBASE_APPID }}
        VITE_FIREBASE_MEASUREMENTID: ${{ secrets.VITE_FIREBASE_MEASUREMENTID }}

    - name: Configure GH Pages
      uses: peaceiris/actions-gh-pages@v3

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        path: ./dist
    
    - name: Deploy
      id: deploy
      uses: actions/deploy-to-github-pages@v2
  