name: Build and Deploy to Github pages

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Build project
        run: npm run build
        env:
          VITE_FIREBASE_YOUTUBE_API_KEY: '${{secrets.VITE_YOUTUBE_API_KEY}}'
          VITE_FIREBASE_APIKEY: '${{ secrets.VITE_FIREBASE_APIKEY }}'
          VITE_FIREBASE_AUTHDOMAIN: '${{ secrets.VITE_FIREBASE_AUTHDOMAIN }}'
          VITE_FIREBASE_PROJECTID: '${{ secrets.VITE_FIREBASE_PROJECTID }}'
          VITE_FIREBASE_STORAGEBUCKET: '${{ secrets.VITE_FIREBASE_STORAGEBUCKET }}'
          VITE_FIREBASE_MESSAGINGSENDERID: '${{ secrets.VITE_FIREBASE_MESSAGINGSENDERID }}'
          VITE_FIREBASE_APPID: '${{ secrets.VITE_FIREBASE_APPID }}'
          VITE_FIREBASE_MEASUREMENTID: '${{ secrets.VITE_FIREBASE_MEASUREMENTID }}'

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v3
        with:
          name: production-files
          path: ./dist

  deploy:
    name: Deploy
    needs: build_and_deploy
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: production-files
          path: ./dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist